import type {Role} from './contracts';
export type Permission='PROJECT_VIEW'|'PROJECT_MANAGE'|'ACTIVITY_UPDATE'|'EVIDENCE_CREATE'|'EVIDENCE_VERIFY'|'BOQ_VIEW'|'INTERNAL_MARGIN_VIEW'|'RFQ_RESPOND'|'PO_VIEW_OWN'|'PAYMENT_STATUS_VIEW_OWN'|'MEASUREMENT_VERIFY'|'CLIENT_PORTAL_VIEW';
const grants:Record<Role,Permission[]>={
OWNER:['PROJECT_VIEW','PROJECT_MANAGE','ACTIVITY_UPDATE','EVIDENCE_CREATE','EVIDENCE_VERIFY','BOQ_VIEW','INTERNAL_MARGIN_VIEW','MEASUREMENT_VERIFY','CLIENT_PORTAL_VIEW'],
STAFF:['PROJECT_VIEW','ACTIVITY_UPDATE','EVIDENCE_CREATE','EVIDENCE_VERIFY','BOQ_VIEW','MEASUREMENT_VERIFY'],
ENGINEER:['PROJECT_VIEW','ACTIVITY_UPDATE','EVIDENCE_CREATE','EVIDENCE_VERIFY','BOQ_VIEW','MEASUREMENT_VERIFY'],
SUPERVISOR:['PROJECT_VIEW','ACTIVITY_UPDATE','EVIDENCE_CREATE','EVIDENCE_VERIFY'],
AGENCY:['PROJECT_VIEW','ACTIVITY_UPDATE','EVIDENCE_CREATE','PAYMENT_STATUS_VIEW_OWN'],
VENDOR:['RFQ_RESPOND','PO_VIEW_OWN','PAYMENT_STATUS_VIEW_OWN'],
ARCHITECT:['PROJECT_VIEW','EVIDENCE_CREATE','EVIDENCE_VERIFY'],CONSULTANT:['PROJECT_VIEW','EVIDENCE_CREATE','EVIDENCE_VERIFY'],
CLIENT:['CLIENT_PORTAL_VIEW'],LABOUR:['EVIDENCE_CREATE']};
export const hasPermission=(roles:Role[],p:Permission)=>roles.some(r=>grants[r].includes(p));
